
[build]
command = "next build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[template.environment]
NETLIFY_CLIENT_ID = "Netlify Client ID"
NETLIFY_CLIENT_SECRET = "Netlify Client Secret"
NEXTAUTH_SECRET = "NextAuth Secret"